name: Build and Deploy Spring Boot Project

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the version you need
          distribution: 'zulu'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --file crud-api/pom.xml

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ramkey
          chmod 600 ~/.ssh/ramkey
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy JAR to EC2
        run: |
          scp -i ~/.ssh/ramkey crud-api/target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/ram_crud_app/

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/ramkey -T ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/ram_crud_app
          # Kill any previously running app
          pkill -f 'java -jar' || true
          # Start the new JAR
          nohup java -jar crud-api-latest.jar > app.log 2>&1 &
          EOF
