name: Deploy to EC2

on:
  workflow_run:
    workflows:
      - Build JAR
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: crud-api-jar

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ramkey
        chmod 600 ~/.ssh/ramkey
        ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

    - name: Transfer JAR file to EC2
      run: |
        scp -i ~/.ssh/ramkey -o StrictHostKeyChecking=no ./crud-api-ram-jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/crud-api-ram-jar

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ramkey -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        pkill -f 'java -jar' || true
        nohup java -jar /home/${{ secrets.EC2_USER }}/crud-api-ram-jar > app.log 2>&1 &
        EOF

