name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Upload JAR as an artifact"]  # Name of the build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: crud-api-ram-jar  # Artifact name must match the name used in build.yml
          path: ./  # Download artifact to the current directory

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/ramkey
          chmod 600 ~/.ssh/ramkey
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ramkey ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/ram_crud_app
          # Kill the old running app if any
          pkill -f 'java -jar'
          # Deploy the new JAR file
          nohup java -jar crud-api-ram-jar > app.log 2>&1 &
          EOF
